In [3]:
import numpy as np

In [23]:
x = np.array([[1, 2], [-1, -2]])

In [24]:
x

array([[ 1,  2],
       [-1, -2]])

In [25]:
1/(1+(np.exp(-1*x)))

array([[ 0.73105858,  0.88079708],
       [ 0.26894142,  0.11920292]])

In [26]:
s=1/(1+(np.exp(-1*x)))

In [27]:
s

array([[ 0.73105858,  0.88079708],
       [ 0.26894142,  0.11920292]])

In [28]:
s.shape

(2, 2)

In [29]:
1-s

array([[ 0.26894142,  0.11920292],
       [ 0.73105858,  0.88079708]])

In [30]:
s*(1-s)

array([[ 0.19661193,  0.10499359],
       [ 0.19661193,  0.10499359]])