In [123]:
import pandas
import numpy as np

In [15]:
x= np.array([1,2])

In [25]:
x=x-np.max(x,axis=0)
x

array([-1,  0])

In [26]:
np.exp(x)

array([ 0.36787944,  1.        ])

In [27]:
np.sum(np.exp(x))

1.3678794411714423

In [28]:
np.exp(x)/np.sum(np.exp(x))

array([ 0.26894142,  0.73105858])

In [30]:
x= np.array([1,2])
x


array([1, 2])

In [32]:
np.exp(x-np.max(x,axis=0))/np.sum(np.exp(x-np.max(x,axis=0)))
x=np.exp(x-np.max(x,axis=0))/np.sum(np.exp(x-np.max(x,axis=0)))
x

array([ 0.26894142,  0.73105858])

In [33]:
x=np.array([[1001,1002],[3,4]])
x

array([[1001, 1002],
       [   3,    4]])

In [35]:
(x.shape)

(2, 2)

In [55]:
x=np.array([[1001,1002],[2000,4],[6,5]])

In [56]:
x


array([[1001, 1002],
       [2000,    4],
       [   6,    5]])

In [66]:
(np.max(x,axis=1))

array([1002, 2000,    6])

In [86]:
(np.max(x,axis=1)).reshape(x.shape[0],1)

array([[1002],
       [2000],
       [   6]])

In [87]:
x-(np.max(x,axis=1)).reshape(x.shape[0],1)

array([[   -1,     0],
       [    0, -1996],
       [    0,    -1]])

In [89]:
np.exp(x-(np.max(x,axis=1)).reshape(x.shape[0],1))/np.sum(np.exp(x-(np.max(x,axis=1)).reshape(x.shape[0],1)))

array([[ 0.09847516,  0.26768323],
       [ 0.26768323,  0.        ],
       [ 0.26768323,  0.09847516]])

In [91]:
x=np.array([[1001,1002],[3,4]])
np.exp(x-(np.max(x,axis=1)).reshape(x.shape[0],1))/np.sum(np.exp(x-(np.max(x,axis=1)).reshape(x.shape[0],1)))

array([[ 0.13447071,  0.36552929],
       [ 0.13447071,  0.36552929]])

In [92]:
[0.26894142, 0.73105858],
[0.26894142, 0.73105858]])
    

IndentationError: unexpected indent (<ipython-input-92-b6706e4719c3>, line 2)

In [100]:
x

array([[1001, 1002],
       [   3,    4]])

In [101]:
x=x-(np.max(x,axis=1)).reshape(x.shape[0],1)

In [102]:
x

array([[-1,  0],
       [-1,  0]])

In [107]:
np.exp(x)

array([[ 0.36787944,  1.        ],
       [ 0.36787944,  1.        ]])

In [108]:
np.sum(x, axis=0)

array([-2,  0])

In [115]:
np.array([[-1001,-1002]])

array([[-1001, -1002]])

In [116]:
np.array([[-1001,-1002]]).shape

(1, 2)

In [121]:
x=np.array([[-1001,-1002]])

In [122]:
x=x-(np.max(x,axis=1)).reshape(x.shape[0],1)
x=np.exp(x)/(np.sum(np.exp(x), axis=1))
x

array([[ 0.73105858,  0.26894142]])

In [124]:
x=np.array([1,2])
x

array([1, 2])

In [126]:
x=np.exp(x-np.max(x,axis=0))/np.sum(np.exp(x-np.max(x,axis=0)))
x

array([ 0.3864837,  0.6135163])