In [2]:
import pandas
import numpy as np

In [4]:
x=np.array([1,2])
x

array([1, 2])

In [5]:
len(x.shape)

1

In [8]:
np.exp(x-np.max(x,axis=0))

array([ 0.36787944,  1.        ])

In [11]:
np.sum(np.exp(x-np.max(x,axis=0)))

1.3678794411714423

In [13]:
x=np.exp(x-np.max(x,axis=0))/np.sum(np.exp(x-np.max(x,axis=0)))
x

array([ 0.26894142,  0.73105858])

In [14]:
x=np.array([[1001,1002],[3,4]])
x

array([[1001, 1002],
       [   3,    4]])

In [15]:
x=x-(np.max(x,axis=1)).reshape(x.shape[0],1)
x

array([[-1,  0],
       [-1,  0]])

In [16]:
x=np.exp(x)/(np.sum(np.exp(x), axis=1)).reshape(x.shape[0],1)
x

array([[ 0.26894142,  0.73105858],
       [ 0.26894142,  0.73105858]])